import { useState, useMemo } from 'react';
import { X, Printer, Clipboard, FileText, TableProperties, Mail } from 'lucide-react';
import { getInterpretation } from '../data/clinicalInterpretations';
import { exportExcel } from '../utils/excelExport';
import BulkEmailPreview from './BulkEmailPreview';

const today = () => new Date().toISOString().split('T')[0];

function formatDate(isoOrYMD) {
  if (!isoOrYMD) return '';
  return new Date(isoOrYMD).toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric'
  });
}

// ── Print window ──────────────────────────────────────────────────────────────

function buildPrintHTML({ groups, grouping, customNote, reportDate, totalCount }) {
  const groupBlocks = groups.map(({ label, patients }) => {
    const rows = patients.map(p => {
      const interp = getInterpretation(p.genotype);
      return `
        <div class="patient-block">
          <div class="patient-header">
            <span class="patient-id">${p.id}</span>
            <span class="priority ${p.priority === 'High' ? 'priority-high' : 'priority-medium'}">${p.priority} Priority</span>
            <span class="genotype">${p.genotype || '—'}</span>
            <span class="phenotype">${p.phenotype || '—'}</span>
          </div>
          ${p.implication ? `<p class="implication"><strong>Clinical implication:</strong> ${p.implication}</p>` : ''}
          ${interp ? `<p class="interp">${interp.reportSummary}</p>` : ''}
          ${p.suggestedAction ? `<p class="action"><strong>Recommended action:</strong> ${p.suggestedAction}</p>` : ''}
          ${p.site ? `<p class="site"><em>Collection site: ${p.site}</em></p>` : ''}
        </div>`;
    }).join('');
    return `
      <div class="group">
        <h3 class="group-title">${label} <span class="group-count">(${patients.length} patient${patients.length !== 1 ? 's' : ''})</span></h3>
        ${rows}
      </div>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>MyAfroDNA Provider Report — ${formatDate(reportDate)}</title>
<style>
  body { font-family: Georgia, serif; max-width: 750px; margin: 40px auto; color: #111; font-size: 13px; line-height: 1.6; }
  h1 { font-size: 20px; margin-bottom: 2px; }
  .subtitle { color: #555; font-size: 12px; margin-bottom: 20px; }
  .meta { display: flex; gap: 30px; background: #f5f5f5; padding: 10px 14px; border-radius: 4px; margin-bottom: 24px; font-size: 12px; }
  .meta span { color: #333; }
  .meta strong { color: #111; }
  .custom-note { background: #fffbeb; border-left: 3px solid #d97706; padding: 10px 14px; margin-bottom: 24px; font-size: 12px; white-space: pre-wrap; }
  h2 { font-size: 15px; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 28px; margin-bottom: 12px; }
  .group-title { font-size: 13px; font-weight: bold; margin: 18px 0 8px; color: #333; }
  .group-count { font-weight: normal; color: #777; }
  .patient-block { border: 1px solid #ddd; border-radius: 4px; padding: 10px 14px; margin-bottom: 10px; break-inside: avoid; }
  .patient-header { display: flex; align-items: center; gap: 10px; margin-bottom: 6px; flex-wrap: wrap; }
  .patient-id { font-family: monospace; font-size: 14px; font-weight: bold; }
  .priority { font-size: 11px; padding: 1px 7px; border-radius: 20px; font-weight: bold; }
  .priority-high { background: #fee2e2; color: #991b1b; }
  .priority-medium { background: #fef3c7; color: #92400e; }
  .genotype { font-family: monospace; background: #f3f4f6; padding: 1px 6px; border-radius: 3px; font-size: 12px; }
  .phenotype { font-size: 12px; color: #555; }
  .implication { margin: 4px 0; font-size: 12px; }
  .interp { margin: 4px 0; font-size: 12px; color: #374151; }
  .action { margin: 4px 0; font-size: 12px; font-style: italic; color: #1d4ed8; }
  .site { margin: 4px 0; font-size: 11px; color: #9ca3af; }
  .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ccc; font-size: 11px; color: #9ca3af; }
  @media print { body { margin: 20px; } }
</style>
</head>
<body>
<h1>MyAfroDNA Recontact Report</h1>
<p class="subtitle">CYP2C19 Pharmacogenomics Study — Confidential Clinical Communication</p>
<div class="meta">
  <span><strong>Report date:</strong> ${formatDate(reportDate)}</span>
  <span><strong>Patients included:</strong> ${totalCount}</span>
  <span><strong>Grouping:</strong> ${grouping === 'provider' ? 'By provider' : grouping === 'priority' ? 'By priority' : 'Ungrouped'}</span>
</div>
${customNote ? `<div class="custom-note"><strong>Note to provider:</strong>\n${customNote}</div>` : ''}
<h2>Patients Requiring Recontact</h2>
${groupBlocks}
<div class="footer">
  Generated by MyAfroDNA Dashboard · ${formatDate(reportDate)} · For authorised clinical use only
</div>
</body>
</html>`;
}

// ── Plain-text clipboard summary ──────────────────────────────────────────────

function buildClipboardText({ groups, reportDate, customNote, totalCount }) {
  const lines = [
    'MYAFRODNA RECONTACT REPORT',
    `Date: ${formatDate(reportDate)}`,
    `Patients: ${totalCount}`,
    '',
  ];
  if (customNote) {
    lines.push('NOTE TO PROVIDER:', customNote, '');
  }
  groups.forEach(({ label, patients }) => {
    lines.push(`=== ${label.toUpperCase()} ===`);
    patients.forEach(p => {
      lines.push(`  ${p.id}  [${p.priority} Priority]  ${p.genotype || '?'}  ${p.phenotype || ''}`);
      if (p.implication) lines.push(`    Implication: ${p.implication}`);
      if (p.suggestedAction) lines.push(`    Action: ${p.suggestedAction}`);
    });
    lines.push('');
  });
  lines.push('---');
  lines.push('Generated by MyAfroDNA Dashboard. Confidential.');
  return lines.join('\n');
}

// ── Main component ────────────────────────────────────────────────────────────

export default function ReportBuilder({
  flaggedPatients, recontactCases,
  providerAssignments, providers,
  emailedPatients, onMarkEmailed,
  onClose,
}) {
  const [selected, setSelected]       = useState(() => new Set(flaggedPatients.map(p => p.id)));
  const [grouping, setGrouping]       = useState('priority');
  const [customNote, setCustomNote]   = useState('');
  const [reportDate, setReportDate]   = useState(today());
  const [copied, setCopied]           = useState(false);
  const [showEmail, setShowEmail]     = useState(false);

  const includedPatients = useMemo(
    () => flaggedPatients.filter(p => selected.has(p.id)),
    [flaggedPatients, selected]
  );

  const groups = useMemo(() => {
    if (grouping === 'priority') {
      const high = includedPatients.filter(p => p.priority === 'High');
      const medium = includedPatients.filter(p => p.priority !== 'High');
      return [
        ...(high.length   ? [{ label: 'High Priority',   patients: high }]   : []),
        ...(medium.length ? [{ label: 'Medium Priority', patients: medium }] : []),
      ];
    }
    if (grouping === 'provider') {
      const map = new Map();
      includedPatients.forEach(p => {
        const caseRec = recontactCases?.[p.id];
        const key = caseRec?.assignedProvider || 'Unassigned';
        if (!map.has(key)) map.set(key, []);
        map.get(key).push(p);
      });
      return Array.from(map.entries()).map(([label, patients]) => ({ label, patients }));
    }
    return includedPatients.length ? [{ label: 'All Patients', patients: includedPatients }] : [];
  }, [includedPatients, grouping, recontactCases]);

  const toggleAll = () => {
    if (selected.size === flaggedPatients.length) {
      setSelected(new Set());
    } else {
      setSelected(new Set(flaggedPatients.map(p => p.id)));
    }
  };

  const toggleOne = (id) => {
    const next = new Set(selected);
    next.has(id) ? next.delete(id) : next.add(id);
    setSelected(next);
  };

  const handleExcel = () => {
    exportExcel({ groups, grouping, customNote, reportDate, providers, providerAssignments });
  };

  const handlePrint = () => {
    const html = buildPrintHTML({ groups, grouping, customNote, reportDate, totalCount: includedPatients.length });
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 400);
  };

  const handleCopy = async () => {
    const text = buildClipboardText({ groups, reportDate, customNote, totalCount: includedPatients.length });
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback: select textarea
    }
  };

  const allChecked  = selected.size === flaggedPatients.length;
  const someChecked = selected.size > 0 && !allChecked;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[92vh] flex flex-col">

        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-gray-100 shrink-0">
          <div className="flex items-center gap-3">
            <FileText size={20} className="text-teal-700" />
            <div>
              <p className="text-xs text-gray-500 uppercase tracking-wide font-medium">Provider Report</p>
              <h2 className="text-lg font-bold text-gray-900">Generate Recontact Report</h2>
            </div>
          </div>
          <button onClick={onClose} className="p-2 rounded-lg hover:bg-gray-100 text-gray-400">
            <X size={20} />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-5 space-y-5">

          {/* Options row */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Grouping</label>
              <select
                value={grouping}
                onChange={e => setGrouping(e.target.value)}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
              >
                <option value="priority">By priority</option>
                <option value="provider">By assigned provider</option>
                <option value="none">Ungrouped</option>
              </select>
            </div>
            <div>
              <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Report Date</label>
              <input
                type="date"
                value={reportDate}
                onChange={e => setReportDate(e.target.value)}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500"
              />
            </div>
            <div className="flex items-end">
              <p className="text-sm text-gray-500">
                <span className="font-semibold text-gray-900">{selected.size}</span> of {flaggedPatients.length} patients selected
              </p>
            </div>
          </div>

          {/* Custom note */}
          <div>
            <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Note to Provider (optional)</label>
            <textarea
              rows={3}
              placeholder="Add a custom message to include at the top of the report…"
              value={customNote}
              onChange={e => setCustomNote(e.target.value)}
              className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 resize-none"
            />
          </div>

          {/* Patient checklist */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Patients to Include</label>
              <button
                onClick={toggleAll}
                className="text-xs text-teal-700 hover:underline font-medium"
              >
                {allChecked ? 'Deselect all' : 'Select all'}
              </button>
            </div>
            <div className="border border-gray-200 rounded-lg divide-y divide-gray-100 max-h-52 overflow-y-auto">
              {flaggedPatients.map(p => (
                <label
                  key={p.id}
                  className="flex items-center gap-3 px-3 py-2.5 hover:bg-gray-50 cursor-pointer"
                >
                  <input
                    type="checkbox"
                    checked={selected.has(p.id)}
                    onChange={() => toggleOne(p.id)}
                    className="accent-teal-600 w-4 h-4 shrink-0"
                  />
                  <span className="font-mono text-sm font-semibold text-gray-900 w-20 shrink-0">{p.id}</span>
                  <span className={`text-xs font-semibold px-1.5 py-0.5 rounded-full shrink-0 ${
                    p.priority === 'High' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'
                  }`}>{p.priority}</span>
                  <span className="font-mono text-xs text-gray-500 shrink-0">{p.genotype || '—'}</span>
                  <span className="text-xs text-gray-500 truncate">{p.phenotype || ''}</span>
                </label>
              ))}
            </div>
          </div>

          {/* Preview */}
          {includedPatients.length > 0 && (
            <div className="border border-gray-200 rounded-lg overflow-hidden">
              <div className="bg-gray-50 px-4 py-2 border-b border-gray-200">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide">Preview</p>
              </div>
              <div className="p-4 space-y-3 max-h-48 overflow-y-auto">
                {groups.map(({ label, patients }) => (
                  <div key={label}>
                    <p className="text-xs font-bold text-gray-700 uppercase tracking-wide mb-1">{label}</p>
                    {patients.map(p => {
                      const interp = getInterpretation(p.genotype);
                      return (
                        <div key={p.id} className="text-xs text-gray-600 pl-2 border-l-2 border-gray-200 mb-2">
                          <span className="font-mono font-semibold text-gray-900">{p.id}</span>
                          {' · '}
                          <span className={p.priority === 'High' ? 'text-red-600 font-semibold' : 'text-amber-600 font-semibold'}>{p.priority}</span>
                          {' · '}{p.genotype || '—'}
                          {interp && <span className="text-gray-400"> — {interp.clinicalSignificance}</span>}
                        </div>
                      );
                    })}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer actions */}
        <div className="flex flex-wrap items-center justify-between gap-3 p-5 border-t border-gray-100 shrink-0">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900 rounded-lg hover:bg-gray-100 transition-colors"
          >
            Cancel
          </button>
          <div className="flex gap-2 flex-wrap">
            <button
              onClick={handleCopy}
              disabled={includedPatients.length === 0}
              className="flex items-center gap-2 px-3 py-2 text-sm font-medium border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-40"
            >
              <Clipboard size={14} />
              {copied ? 'Copied!' : 'Copy'}
            </button>
            <button
              onClick={() => setShowEmail(true)}
              disabled={includedPatients.length === 0}
              className="flex items-center gap-2 px-3 py-2 text-sm font-medium border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-40"
            >
              <Mail size={14} />
              Email report
            </button>
            <button
              onClick={handleExcel}
              disabled={includedPatients.length === 0}
              className="flex items-center gap-2 px-3 py-2 text-sm font-medium border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-40"
            >
              <TableProperties size={14} />
              Download Excel
            </button>
            <button
              onClick={handlePrint}
              disabled={includedPatients.length === 0}
              className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-teal-700 hover:bg-teal-800 rounded-lg transition-colors disabled:opacity-40"
            >
              <Printer size={14} />
              Print / PDF
            </button>
          </div>
        </div>
      </div>

      {showEmail && (
        <BulkEmailPreview
          patients={includedPatients}
          providers={providers}
          providerAssignments={providerAssignments}
          emailedPatients={emailedPatients}
          onMarkEmailed={onMarkEmailed}
          onClose={() => setShowEmail(false)}
        />
      )}
    </div>
  );
}
